steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', '${_GCF_NAME}', '--runtime', 'go111', '--trigger-topic', '${_PUBSUB_TOPIC}', '--entry-point', 'ScrapeSagarin']
  dir: 'cloud-functions/sagarin'
